### PR TITLE
Noise level 0 support.

### PR DESCRIPTION
**Pull request by YukihoAA**
Hello everyone

This is PR for #63 

I tested in Windows for 3 pc: Intel i3 / AMD R9 280X / CUDA 940MX
also, i tested in ubuntu for Intel Xeon E5-2676

### CODE REVIEW

**Comment by DeadSix27** [comment]
Thanks :)! 

- "add upconv models"

I didn't want to add those for size reasons as long we don't use them.. the models are so big.. I wonder if we should make it a seperate git repo and just make it a submodule.. but again why? we do not use them actively.

- `"Add system environment variables CUDA_TOOLKIT_ROOT_DIR to your CUDA Toolkit path (ex: `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0`)"`

Weird, the cuda installer automatically added itself to path for me each time.. so I figured mentioning this isn't needed.
- `disabled install models option in windows`

Funny, I had the same idea in my head of adding that.

**Comment by DeadSix27** [comment]
Looks fine. By the way, can you merge yourself after review? Or can only owner merge, please test with this PR.

**Comment by YukihoAA** [comment]
OK, I can merge PR. It looks fine.

**Comment by DeadSix27** [comment]
@YukihoAA good, thanks :)

**Pull request merged**
