### PR TITLE
Fix PR #55

### PR DESCRIPTION
**Pull request by YukihoAA**
Add png to no extension output.

### CODE REVIEW

**Comment by YukihoAA** [comment]
Is there any chance that lastSlash == npos ?

I'm curious about that.

**Comment by DeadSix27** [comment]
size_t lastSlashPos = outputFileName.find_last_of("/\\"); you mean?
It's npos if there is no \/, no?

**Comment by YukihoAA** [comment]
I tought outputfilename will always have \//.
But if user put wrong path, It can be. So lastSlash != npos is necessery.

This PR is ready to mearged! (includes #55)

@DeadSix27

**Comment by DeadSix27** [comment]
yes, works fine, thanks! Needs a check for supported output formats, but merged for now.

**Comment by YukihoAA** [comment]
@DeadSix27 Maybe we can add try catch around imwrite to check it actually supported (and writen) or not

**Comment by DeadSix27** [comment]
@YukihoAA I found: cv::getBuildInformation(),

Compile and check output:
```
#include <opencv2/opencv.hpp>
 
int main(void)
{
  std::cout << cv::getBuildInformation() << std::endl;
}
```
Maybe we could parse and check this when starting (and opencv is compiled in)

It shows us:
```
JPEG:                        /lib64/libjpeg.so (ver )
WEBP:                        /lib64/libwebp.so (ver encoder: 0x020e)
PNG:                         /lib64/libpng.so (ver 1.6.34)
TIFF:                        /lib64/libtiff.so (ver 42 / 4.0.9)
JPEG 2000:                   /lib64/libjasper.so (ver 2.0.14)
```

If TIFF for example isn't supported it w ill say "NO".

**Comment by DeadSix27** [comment]
@YukihoAA https://github.com/DeadSix27/waifu2x-converter-cpp/commit/2eda99dc5cf28bf48bab540220a2840a025b7a5c Opinion?

**Comment by YukihoAA** [comment]
@DeadSix27 Great, We can check supported format with less dependance than hard coding it. Also, we can easily check availablity in preprocess which is better than try-catch. (try - catch will works in postprocess and it needs loop)

Good job!

**Comment by DeadSix27** [comment]
@YukihoAA I wonder if we should still add try/catch in case checks fail of if that would be overdoing it.

**Pull request merged**
