### PR TITLE
 Minor code cleanup

### PR DESCRIPTION
**Pull request by iame6162013**
Less repetition, less arguments to one of the functions. 
Behavior should be identical except that windows should get a bit further without crashing on unicode input files.

### CODE REVIEW

**Comment by iame6162013** [comment]
> Refactor w2xconv.cpp a bit

Looks a *lot* more drastic than it really is.

**Comment by DeadSix27** [comment]
Will check it and merge it in later (as well as my VS update), expect it in the next 48hrs

**Comment by iame6162013** [comment]
If there are any more issues let me know.

**Comment by DeadSix27** [comment]
Can you make a simple change log for the features you added/removed/fixed/changed ?

**Comment by iame6162013** [comment]
Certainly, I'll try to do it asap. I can't give a time frame for it sadly.

**Comment by DeadSix27** [comment]
@iame6162013 no hurry

**Pull request merged**
