### PR TITLE
remake W2Mat class

### PR DESCRIPTION
**Pull request by YukihoAA**
This PR will fix segfault issue #122

It won't fix wrong result but it will prevent segfault.

feel free to test this.

### CODE REVIEW

**Comment by YukihoAA** [comment]
I reverted unified find_last_of because it will conflict with PR #134 

this PR can be merged separate with PR #134

**Comment by DeadSix27** [comment]
What's the cause of the wrong result anyway?

**Comment by YukihoAA** [comment]
Segfault => W2Mat
Wrong result => I don't know but this PR is not reason of this.

only 6500x6500+ size image affects this PR.

**Comment by YukihoAA** [comment]
Oh i tagged wrong issue number. i edited.

**Comment by DeadSix27** [comment]
Are you done on this PR @YukihoAA ?

**Comment by YukihoAA** [comment]
@DeadSix27 at this point.. i have no idea with that result. i'll create separate PR if I found reason of that.

**Comment by DeadSix27** [comment]
Okay, I'll wait with testing/review then.

**Comment by YukihoAA** [comment]
I did not implemented some functions that is not essential but I'll make that functions and open new PR.

**Pull request closed without merging**
