### PR TITLE
Make it compile on macOS

### PR DESCRIPTION
**Pull request by inflation**
There are some changes after Sierra and the code does not compile. So I fixed those issues.

### CODE REVIEW

**Comment by DeadSix27** [comment]
What's with the changes to  src/w2xconv.cpp  src/main.cpp include/picojson.h ??

**Comment by inflation** [comment]
Old picojson.h won't compile so I updated to the latest version. They solved the issues in that commit.

Other files maybe because my default settings treat all warnings to be errors, so I fixed them too. Should be no actual changes at all.

**Comment by DeadSix27** [comment]
picojson.h update should be a seperate PR.

Please don't change the other files, unless its a cleanup/bugfix which also goes into a new PR. (src/main.cpp,  src/w2xconv.cpp)

**Comment by inflation** [comment]
Aye aye, captain.

**Pull request closed without merging**
