### PR TITLE
Re-implementation of W2Mat

### LINKED ISSUE #122: Upscaling very large images got crashed result
When trying to upscale an image of 6416x8592 resolution I got a segmentation fault , to easily be able to reproduce this issue I created a 7000x7000 file with imagemagick:
```
~ » convert -size 7000x7000 xc:white white.png && waifu2x-converter-cpp -s -i white.png
CUDA: GeForce GTX 1080
[1]    29734 segmentation fault (core dumped)  waifu2x-converter-cpp -s -i white.png
```
[Full output without `--silent`](https://gist.github.com/Kattus/e8ec2d30f18797d956f73c0e0fda8e69)

I'm fairly certain it has nothing to do with running out of memory as there's plenty available:
screenshot

VRAM/GPU ruled out, still crashes when using `--disable-gpu`:
https://gist.github.com/Kattus/4dd7871633d2bb89760426c31b99881f

I could upscale this and similar images just fine using waifu2x-caffe, but I am no longer using Windows so it is not an option unfortunately. Any help with this would be greatly appreciated, even if perhaps just a workaround.

### PR DESCRIPTION
**Pull request by YukihoAA**
There was possible chance of memory fault in previous version of W2Mat.

Previous version of W2Mat won't be problem in most of the time because our program always using stack one direction.

but our program runs in multi-thread, so it can cause memory fault during operation.

what i did is made data to return by arguments not just returning,

so It will not produce dangling pointer anymore.

This PR doesn't fix issue #122, but this PR will be help.

### CODE REVIEW

**Comment by YukihoAA** [comment]
Works fine with Ubuntu & Windows

**Comment by YukihoAA** [comment]
The output Image size limit is around 13370 and this issue is about size limit due to we use INT_MAX everywhere. (in my test, output image 13370*13370 is limit size of square image)

in our convert function you can easily find width and height is int char, that is 32bit.

13370 is nearly limit of int. 

root(0xFFFF FFFF div 24) = 13,377.479957....

so i think it is limit of image size. (INT_MAX)

I tried to proof exact limit buf size of image is INT_MAX but i cannot because of lines like this.

image


This is not openCV 's problem and it is our problem, but I don't think we have to support huge image like this... (opencv can read/write this big image)

or we may consider split images in small pieces and run w2x and combine them out side of libw2x (libw2x's Buffer class only supports INT_MAX)

if we want to support this issue, i think split image is best idea.

**Comment by DeadSix27** [comment]
This may seem obviously wrong but, Is it impossible to switch to long int or similar? 

Otherwise I guess it wouldn't be too hard to split the image /4 and iterate over each part the same we already do over the whole image.

**Comment by YukihoAA** [comment]
I have no idea with CL or CUDA but they may uses int too.

So i think it is more safe to implement divide in 4 pieces or max_image_size or something is better.

**Pull request merged**
