### PR TITLE
misc: move to stable std::filesystem

### LINKED ISSUE #206: TTA support
I've noticed that there's TTA support on waifu2x-snowshell_v2.1 using waifu2x-converter-cpp.exe  version: v5.3.1 (tta-support-ee162a4). 

But on the CLI version using waifu2x-converter-cpp.exe  version: v5.3.1 (master-c85a525), there's no TTA support.

### PR DESCRIPTION
**Pull request by DeadSix27**
Fixes build error with latest MSVC version

Please test these changes on x86(_64) Linux, I was only able to test on Raspberry Pi3 Arch-ARM and Windows 10/MSCV-latest

Resolves #206 due to new release after this gets merged.

### CODE REVIEW

**Comment by Kattus** [comment]
Compiled this on Arch and used it on a few images both with and without TTA, didn't notice anything out of the ordinary.

**Comment by Equim-chan** [comment]
Note that on llvm9, `-lc++fs` is deprecated and both `<filesystem>` and `<experimental/filesystem>` can be used directly now. See https://libcxx.llvm.org/docs/UsingLibcxx.html#using-filesystem

**Comment by DeadSix27** [comment]
@Equim-chan Feel free to add a PR for that based on the `use-stable-filesystem` branch.

**Comment by Equim-chan** [comment]
@DeadSix27  I'm not so familiar with conditions and flows in CMake file... 😭

**Comment by DeadSix27** [comment]
@Equim-chan Mind testing: https://github.com/DeadSix27/waifu2x-converter-cpp/commit/9e34a6db4c7504e785e54acaaebc8b1a0a0fc3e8

**Comment by Equim-chan** [comment]
@DeadSix27 I tried, it doesn't work. `-lc++fs` is still attached.

**Comment by DeadSix27** [comment]
Ahhh I see: 
> As of CMake 3.0.0 the CMAKE_<LANG>_COMPILER_ID value for Apple-provided Clang is now AppleClang.
...

**Comment by DeadSix27** [comment]
@Equim-chan Can you test whether @YukihoAA's changes work on macOS?

**Comment by Equim-chan** [comment]
It works.

**Pull request merged**
