### PR TITLE
add quality and format options

### PR DESCRIPTION
**Pull request by DeadSix27**
Any objections? @YukihoAA 

And do you mind testing it?

~~**EDIT:** To further improve this a format options needs to be added, e.g:~~

~~`-f --format (png/jpg/webp/...)` Which sets the format when running in recursive/folder mode, as currently theres no way to do that.~~

^this has been added now.

### CODE REVIEW

**Comment by YukihoAA** [comment]
I checked and It works fine.

I have some question about default quality option.
As @K4YT3X said, Waifu2x is made for image improvements.
So how about set default quality value to 100? 

We can set it to 100 manually so 90 is fine too

**Comment by K4YT3X** [comment]
> So how about set default quality value to 100?

I agree with the range of 90-100. If the output quality is bad, upscaling loses its purpose.
Just my 2 cents though, I don't have such extensive knowledge about this program.

**Comment by DeadSix27** [comment]
@YukihoAA @K4YT3X 
If you use JPEG over PNG, quality is obviously not your goal, you probably want to save some space..so I feel like 90 is even too high, should be 70.
What we need to find is the perfect % where its impossible to see compression artifacts.

Feel free to compare.

Also up for question is PNG compression, I tested 0 to 9 on my 6700k OC'd to 4.6GHz:

| compression level | time in seconds | size in MB |
|-------------------|-----------------|------------|
| 9 | 7.05050  |  2.90 |
| 8 | 4.94349  |  2.92 |
| 7 | 2.66766  |  2.98 |
| 6 | 2.36425  |  3.01 |
| 5 | 2.07723  |  3.09 |
| 4 | 1.93120  |  3.17 |
| 3 | 1.95937  |  3.28 |
| 2 | 1.89655  |  3.41 |
| 1 | 1.87718  |  3.50 |
| 0 | 1.80770  | 12.39 |

I feel like 6 or 5 is the perfect middle. (currently its 5)

**Comment by YukihoAA** [comment]
> If you use JPEG over PNG, quality is obviously not your goal

It make sense, OK. actually JPEG is lossy format so if someone wants to make lossless output, they should PNG instead. 90% is loosy but it is fit to purpose of saving some disk space. (100% is loosy too.)

**Comment by DeadSix27** [comment]
Exactly

**Pull request merged**
