### PR TITLE
Support huge Image conversion.

### LINKED ISSUE #122: Upscaling very large images got crashed result
When trying to upscale an image of 6416x8592 resolution I got a segmentation fault , to easily be able to reproduce this issue I created a 7000x7000 file with imagemagick:
```
~ » convert -size 7000x7000 xc:white white.png && waifu2x-converter-cpp -s -i white.png
CUDA: GeForce GTX 1080
[1]    29734 segmentation fault (core dumped)  waifu2x-converter-cpp -s -i white.png
```
[Full output without `--silent`](https://gist.github.com/Kattus/e8ec2d30f18797d956f73c0e0fda8e69)

I'm fairly certain it has nothing to do with running out of memory as there's plenty available:
screenshot

VRAM/GPU ruled out, still crashes when using `--disable-gpu`:
https://gist.github.com/Kattus/4dd7871633d2bb89760426c31b99881f

I could upscale this and similar images just fine using waifu2x-caffe, but I am no longer using Windows so it is not an option unfortunately. Any help with this would be greatly appreciated, even if perhaps just a workaround.

### PR DESCRIPTION
**Pull request by YukihoAA**
Yes! now we can convert any size of images. lol

If input image is larger than 6000*6000, now it will be sliced in to 4 pieces.

if input is bigger than 12000, no problem it will slices in to 16 pieces. but are you have enough memory to convert it? wwww

if you memory's are 128GB or something it could be sliced in to 32 or even 64 pieces so

There is no image size limit anymore. (but maybe opencv does?)

feel free to test this.

EDIT: I tested in Ubuntu(Intel FMA) and Windows(CUDA) by 7000x6904

fixes #122

### CODE REVIEW

**Comment by YukihoAA** [comment]
in this commit, I combined unicode functions in to one functions like i did in #134 

So I request this PR merged before any other commits because it will cause conflict.

**Comment by Kattus** [comment]
I'll give this a test tonight

**Comment by DeadSix27** [comment]
> There is no image size limit anymore. (but maybe opencv does?)

Afaik, theres no limit on cv::Mat as long you have the memory for it.
I also found this `https://github.com/opencv/opencv/pull/11505` 
They handle images > max_int the same way we do now.


About this PR, I found a few bugs:
`--scale-ratio 2` on 7000x9670 = Image looks fine
`--scale-ratio 3` on 7000x9670 = Images out of order. (see example at bottom) (And apparently hue-changed)
`--scale-ratio 6` on 7000x9670 = Crash:
`Exception thrown at 0x00007FFA9191C69E (w2xc.dll) in waifu2x-converter-cpp.exe: 0xC0000005: Access violation writing location 0x0000000000000000.`
During memcpy, probably out of memory. (Needs a proper error possibly?)

Out of order example:
image

**Comment by YukihoAA** [comment]
oh.... i forgot we can scale up more than 2.0..... (....)

i'll fix it tomorrow.

i have to limit input size not 6000x6000, 

pow((12000 / scale_ratio),2)

**Comment by DeadSix27** [comment]
Yep, Looking at the code I noticed it didn't seem to handle ratio's hence why i tested that first.

**Comment by Kattus** [comment]
Aside from what DeadSix27 said, would it be possible to do the combining with several cores instead of one? it's very very slow on my CPU.

**Comment by YukihoAA** [comment]
It prints out combining but actually the time spent is due to file. not combine.

I'll add that description log.

**Comment by YukihoAA** [comment]
image

Ah.. my laptop is too slow to test this.. when does it finished T_T

feel free to test this. i added some commits to solve problems mentioned.

**Comment by YukihoAA** [comment]
previous code  does not work and i took 3hr to test that........

I need someone to test this thing with me... i updated code to slice much smaller.

**Comment by YukihoAA** [comment]
ye, much better

image

**Comment by YukihoAA** [comment]
@Kattus I found merging takes long time too, when physical memory is not enough to proceed concat image. 

waifu2x uses pagefile automatically when physical memory is not enough, as page file works like cash and it is disk so it should be slow

**Comment by YukihoAA** [comment]
input = 7000x6904 / x3.0 scale passed test

image

**Comment by Kattus** [comment]
> @Kattus I found merging takes long time too, when physical memory is not enough to proceed concat image.
> 
> waifu2x uses pagefile automatically when physical memory is not enough.
> 
> As pagefile works like cache and it is disk so it should be slow

I have plenty of RAM available though, and swap usage didn't increase either.
sysmon
You can clearly see where the merging starts as one core maxes out at 100% for a long time.

**Comment by YukihoAA** [comment]
@kattus 

> It prints out combining but actually the time spent is due to file. not combine.
> 
> I'll add that description log.

It is file write then.

**Comment by DeadSix27** [comment]
I always test on an NVMe disk, possibly should start testing on a HDD.

**Comment by Kattus** [comment]
This was done using an NVMe SSD as well.

**Comment by YukihoAA** [comment]
This is what i got during final merge of scale_ratio 6.

you can see physical memory is not full but disk i/o is 100% during hconcat() and vconcat()

image

**Comment by DeadSix27** [comment]
It works fine for me. barely any CPU usage the entire time, max is 10%.

Writing is understandably slow, took like 10s.

**Comment by YukihoAA** [comment]
I've got pass on 7000x6904 / x6.0 scale passed test in windows

I have no linux machine with VGA, so.. someone needs to test in Linux.

image

**Comment by DeadSix27** [comment]
PS: Scale-ratio 5 on 7000x6*, is where I run into images being buggy again, as 1 single is 8000x*, running back into the int_max issue we had originally, needs more slices.

**Comment by YukihoAA** [comment]
you can get output in step by step in working dir of your waifu2x-converter-cpp

image

image

at this point, we print all of output in step so it must be slow. 

image

**Comment by YukihoAA** [comment]
@DeadSix27 I already slice pieces much smaller to fix that probelm. you can test them again at this point.

**Comment by DeadSix27** [comment]
@YukihoAA Ah, I reset and pulled but one file must've had been opened somewhere and didn't get updated.

(As I had the new debug stuff for some reason, but not the new logic to merge during --scale-ratio)

**Comment by YukihoAA** [comment]
you don't need --silence because i already disabled Iteration stuff by passing false to them in
aac050c

**Comment by DeadSix27** [comment]
Too spammy still. Use silent now it's easier to read.

**Comment by DeadSix27** [comment]
Doing further testing, I got a confirmation on what I suspected would happen once we splice images like this..:
image

Left scaled with splices, right scaled without splices.

As you can see on the edges of every spliced image there are distortions.

**Comment by YukihoAA** [comment]
ah... It happened...

 I thought this can be occur....

**Comment by DeadSix27** [comment]
Ye I don't know if we can even fix this? It's down to the models isn't it?

overcut the images? e.g make the splices 20px bigger than they have to be, then cut off the 20x?

**Comment by YukihoAA** [comment]
it could be solution

**Comment by YukihoAA** [comment]
@DeadSix27 ah.. we cannot use hconcat() and vconcat() then..

**Comment by DeadSix27** [comment]
How so? At the end of the hacky cut 20px-bigger task we cut the 20px off and then the result will be the same size as the quarters in xconcat() ?

**Comment by YukihoAA** [comment]
slicing function is not working over x128 scale.

slicing function works like this>
1. slice to make image under 8000*8000 / scale / scale
2. w2x slices
3. merge them

but when it scales 256 or something, image block became 31px. output quality is not good at that small size. (limit at this moment is 62px, it is not good either but.. better then 31px)

if someone complains about limited x128 conversion (it was not supported in past too!)

re-implementation must be like this>

1. check image is bigger then 8000x8000 & if it is slice that under 8000
2. w2x for 2x scale (not input scale_factor)
3. check slices is bigger then 8000x8000 & slice
4. loop to 2~4 until loop count is (int) ceil(log2(scale_factor))
5. check slice size & slice
6. scale down it
7. merge tons of slices

I won't implement that.

**Comment by DeadSix27** [comment]
Works fine on my end, however max is ratio 4x on 7000px images, after that it crashes without errors, due to too little RAM.

Apart from that it seems to work fine (on Windows anyway)

**Comment by YukihoAA** [comment]
@DeadSix27 maybe add some warning text before start slicing?

"Warning: This image is too big, It can cause out of memory error"

**Comment by DeadSix27** [comment]
@YukihoAA sounds alright but, @Kattus has a segfault problem still.

**Comment by Kattus** [comment]
While DeadSix talks about running out of RAM, this is not the case for me (on linux).
[ramusage](https://too.lewd.se/21463ac4ffea_2019-05-09_16-00-06.webp)

Trying to scale a 7000x7000 by x5 or higher results in a segfault. 4x is fine.

**Comment by YukihoAA** [comment]
I'll call senko-san

**Pull request closed without merging**
