### PR TITLE
Add some supported output format & Code Improvement

### PR DESCRIPTION
**Pull request by YukihoAA**
edited opencv 300 to 330 and deleted duplicate option in MINGW compile.

(opencv_hal300 was mentioned twice)

### CODE REVIEW

**Comment by DeadSix27** [comment]
Does the mingw compile actually work for you? I couldn't get it working.

**Comment by YukihoAA** [comment]
I didn't tested with MINGW.
But I thought opencv300 is definitively incorrect version number so I just edited for improvement.

I added commit to support more output format in imwrite.

base on https://docs.opencv.org/3.3.0/d4/da8/group__imgcodecs.html

I'm not sure .EXR can be always supported. but I couldn't find any constraint condition and actually it is working now.

**Comment by YukihoAA** [comment]
Added more code improvements.

**Comment by DeadSix27** [comment]
@YukihoAA Thank you :), Ill test later and merge it.

**Comment by YukihoAA** [comment]
I tested this code on MINGW. 
I realized that commit 78f2c22 does not mean anything.
I reverted my commit 78f2c22 .

**Comment by DeadSix27** [comment]
@YukihoAA I tested it on arch and win64 now, works fine and no more warnings :)

**Comment by DeadSix27** [comment]
@YukihoAA PS: I was going to increase version now and make a new windows release, do you have anything else to add?

**Pull request merged**
