### PR TITLE
Fix output filename when no path was specified (was adding extension …

### PR DESCRIPTION
**Pull request by matfrem**
…even if there was already an extension)

### CODE REVIEW

**Comment by DeadSix27** [comment]
It should still append .png/default to png if no extension is specified though. (which it now doesn't)

On that note, now that different extensions can be supplied, we should check for opencv supported formats, See:
https://docs.opencv.org/3.0-beta/modules/imgcodecs/doc/reading_and_writing_images.html#imread
https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp#L136

Either by finding out if opencv has a function for that or just hardcoding w2x to only allow for tiff/jpg/png/bmp, but that could still cause ppl to crash out with: `OpenCV Error: Unspecified error (could not find a writer for the specified extension) in imwrite_, file /home/*/aur/opencv-git/src/opencv/modules/imgcodecs/src/loadsave.cpp, line 680`

**Comment by YukihoAA** [comment]
Yes, ".png" should be added. That code was improved by me to prevent crash. so this PR should not merged.

**Comment by DeadSix27** [comment]
Not until that's fixed, yes, but there is a bug indeed, in that other formats aren't supported.

**Comment by YukihoAA** [comment]
OK I founded the problem

**Comment by YukihoAA** [comment]
@DeadSix27 Please check my PR #57

**Pull request merged**
