### PR TITLE
Allow for recursive operation.

### PR DESCRIPTION
**Pull request by iame6162013**
- Added the ability to enter a directory as the program input, this  allow the program to process on all files in this directory.
- Created an option to go deeper from the input directory into other directories.
- goto error replaced with throw system.

May I know your opinion about this PR?

### CODE REVIEW

**Comment by DeadSix27** [comment]
Any chance you can look into: https://github.com/DeadSix27/waifu2x-converter-cpp/issues/4 ?
I do not have the time currently and that issue is one of the biggest in my opinion.

**Comment by soimort** [comment]
IMHO, this PR breaks stuff. First, it no longer parses input file names with whitespaces in them: (while the old code does)

```
$ ./waifu2x-converter-cpp --scale_ratio 2 -i 'in (1).png' -o out.png
PARSE ERROR: Argument: -i (--input)
             More than one valid value parsed from string 'in (1).png'

Brief USAGE: 
   ./waifu2x-converter-cpp  [--list-processor] [--block_size <integer>]
                            [--disable-gpu] [--force-OpenCL] [--processor
                            <integer>] [-j <integer>] [--model_dir
                            <string>] [--scale_ratio <double>]
                            [--noise_level <1|2|3>] [-m <noise|scale
                            |noise_scale>] [-r <bool>] [-o <string>] -i
                            <string> [--] [--version] [-h]

For complete USAGE and HELP type: 
   ./waifu2x-converter-cpp --help
```

Second, `generate_output_location` does not handle output names like `out.png` correctly, but just throws a `std::runtime_error` instead. (which is a frustrating way of *abusing* C++ exceptions.)

```
$ ./waifu2x-converter-cpp --scale_ratio 2 -i in.png -o out.png 
CPU:        Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
terminate called after throwing an instance of 'std::runtime_error'
  what():  An unknown error occured.
[1]    13146 abort      ./waifu2x-converter-cpp --scale_ratio 2 -i in.png -o out.png
```

**Comment by iame6162013** [comment]
Huh, the first error is odd, but there is an easy work around.
Wow, the second issue was also extremely stupid, thanks for reporting that!
I'll make a pull request for it soonTM

**Comment by DeadSix27** [comment]
@iame6162013 Another issue, which should be fixed before I actually make a release:

`cv::imwrite("test_folder_scaled/G:\w2x\test_folder_of_images\8188430(noise_scale)(Level1)(x4.000000).png") failed`
`waifu2x-converter-cpp.exe -i test_folder_of_images --scale_ratio 4 -o test_folder_scaled`

Mass conversion output folder and names is not handled correctly.

It should work as follows:

`-i folder_of_images` without defining output folder, should place the scaled images in the same folder as we used to input. e.g `folder_of_images/1.png -> folder_of_images/1_scaled.png`

And if you define an output folder it should put the scaled images into those.

**Pull request merged**
