### PR TITLE
Fix GCC 10 compile errors

### PR DESCRIPTION
**Pull request by Wykerd**
Fixed issue #240 by adding stdio.h include headers to src/threadPool.cpp

### CODE REVIEW

**Comment by Kattus** [comment]
Sadly doesn't  fix it, but at least the error did change!
https://gist.github.com/Kattus/8e16fcae74eb561040368b021b424d77

**Comment by Wykerd** [comment]
@Kattus Are you building it using the AUR package?

The fix worked for me when I built it from my git repo on Archlinux kernel version 5.6.12 with GCC 10.1.0; OpenCV 4.3.0-7; OpenCL 2.2; CUDA 10.2.89-5

**Comment by Kattus** [comment]
@Wykerd I did, used https://aur.archlinux.org/packages/waifu2x-converter-cpp-git/ but applied this as a patch, also tried to replace source to your own repo but errors were identical (I checked with diff)

Anyway it doesn't seem to do anything wacky so I don't see how it works for you but not me.

linux-zen 5.6.13.zen1-1
gcc 10.1.0-1
opencv 4.3.0-7
opencl-headers 2:2.2.20170516-2
cuda 10.2.89-5

so only change is that I use the linux-zen kernel, I'll try using the stock kernel next.

**Comment by Wykerd** [comment]
@Kattus I've tried compiling it using the AUR package's method by passing the -DCMAKE_BUILD_TYPE='Release' flag to cmake and I got the same error you have.

The build instructions for linux in the BUILDING.md files says to simply call `cmake ..` without any flags.

**Comment by Wykerd** [comment]
The stdio header had to be included before thread :-)

**Comment by Kattus** [comment]
Yup that made it compile again, cheers! :)

**Comment by YukihoAA** [comment]
is #227 can solved by this PR?

**Pull request merged**
