### PR TITLE
Add verbose cmdarg

### PR DESCRIPTION
**Pull request by iame6162013**
This removes all console spam, one downside is that you don't know if the program locked up when there is a need to process a large file. (I've never had the program lock up)

This change does not add a pretty output method of the previously outputted spam.

### CODE REVIEW

**Comment by iame6162013** [comment]
See #25

**Comment by DeadSix27** [comment]
Can you change it to default to verbose mode?

**Comment by iame6162013** [comment]
Nvm, ignore that commit

**Comment by DeadSix27** [comment]
Why ignore it?

**Comment by iame6162013** [comment]
(I had to leave without making a better comment sorry)
While it does give the right results e.g. ` ./waifu2x-converter-cpp -v 0 -i ./test_ʤ_/_ʤ_.png ` results in no spam.

I think it's unidiomatic, and would be better if we made it into a 'silent' cmd argument?
What do you say?

**Comment by DeadSix27** [comment]
Make it, -q/quiet, an optional argument. When passed it will silence the output, when not, default verbose behavior will show

**Comment by iame6162013** [comment]
Should that option also mute files like these?

`std::cout << "Operating on: " <<`

**Comment by iame6162013** [comment]
We could always add a second 'completely quiet' argument later

**Comment by iame6162013** [comment]
Adds the suggestions above except for 'completely quiet', don't see a use for it.

**Comment by DeadSix27** [comment]
Alright. I just think quiet was a better naming since verbosity is usually used when it comes to many different levels of it, where as quiet mode is either complete silence or full verbosity which is more applicable in this scenario.

**Pull request merged**
